version: "3"
services:
 redis:
   image: redis
   restart: on-failure
 avrop:
  container_name: avrop-lakemedelsnara-produkter
  image: vgr/avrop-lakemedelsnara-produkter:5.0.7-latest
  platform: linux/amd64
  ports:
   - 8080:8080
  volumes:
   - /opt/data:/opt/data
