version: "3"
services:
 redis:
   image: redis
   restart: always
 avrop:
  container_name: avrop-lakemedelsnara-produkter
  image: vgr/avrop-lakemedelsnara-produkter
  ports:
   - 8080:8080
  volumes:
   - /opt/data:/opt/data
